# Generated by Django 3.1 on 2020-09-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20200919_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
