# Generated by Django 3.1 on 2020-09-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20200919_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
