# Generated by Django 3.1 on 2020-09-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
