# Generated by Django 3.1 on 2020-09-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20200925_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='viewer_count',
            field=models.IntegerField(default=0),
        ),
    ]
